# Mushrooms Classification

Kerakli kutubxonalarni yuklab olamiz

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
df = pd.read_csv("../data/raw/mushrooms.csv")
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [3]:
df.shape # DataFrame hajmini ko'rish

(8124, 23)

In [4]:
df.info() # Boshlang'ich malumotlarni chiqrib olamiz

<class 'pandas.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   str
 1   cap-shape                 8124 non-null   str
 2   cap-surface               8124 non-null   str
 3   cap-color                 8124 non-null   str
 4   bruises                   8124 non-null   str
 5   odor                      8124 non-null   str
 6   gill-attachment           8124 non-null   str
 7   gill-spacing              8124 non-null   str
 8   gill-size                 8124 non-null   str
 9   gill-color                8124 non-null   str
 10  stalk-shape               8124 non-null   str
 11  stalk-root                8124 non-null   str
 12  stalk-surface-above-ring  8124 non-null   str
 13  stalk-surface-below-ring  8124 non-null   str
 14  stalk-color-above-ring    8124 non-null   str
 15  stalk-color-below-ring    8124 non-null   str
 16  veil-type                 8124 non-null   str
 17  veil-color                8124 non-null   str
 18  ring-number               8124 non-null   str
 19  ring-type                 8124 non-null   str
 20  spore-print-color         8124 non-null   str
 21  population                8124 non-null   str
 22  habitat                   8124 non-null   str
dtypes: str(23)
memory usage: 1.4 MB

In [5]:
df.isna().sum() # NaN qiymatlar bor yoki yo'qligini tekshiramiz

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

**Endi navbat matinli ustunlar bilan ishlaymiz**  
Matinli ustunlar bilan ishlashda biz Label Encoding yoki One-Hot Encoding ishlatishimiz kerak.  

**Label Encoding** -- bu ustundagi har bir unique qiymatni raqamlar bilan almashtiradi.  
Bu usul bizning holatga mos keladimi. To'liq emas! Nega?  
Sabab bir necha unique qiymatlarni Label Encode qilganimizda (p, q, s -- 0, 1, 2) model buni 2 0 dan ko'ra muhum deb o'ylaydi.  
Shu sabab biz bu usulni faqat ikkita unique categoryaga ega ustunlarga qo'llaymiz.

**One-Hot Encoding** -- Bu usul aynan categoriyalar bir biridan ustun bo'lmagan bir necha unique categorylar bor holat uchun.
Lekin bu usulda agar unique qiymatlar soni juda muhum. Shu sabab biz buni tekshirishimiz kerak.

In [6]:
def unique_values(col):
    if len(col.unique()) > 2:
        return len(col.unique())
    else:
        return 0

In [7]:
unique_vals = df.apply(unique_values)
unique_vals

class                        0
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      0
odor                         9
gill-attachment              0
gill-spacing                 0
gill-size                    0
gill-color                  12
stalk-shape                  0
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    0
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

In [8]:
# Unique qiymatlari 2 tada ko'p va kam bo'lgan ustunlarni ajratib olamiz
zero_cols = unique_vals[unique_vals==0].index
cols = unique_vals[unique_vals != 0].index

**Label Encoder**

In [10]:
label_encoder = LabelEncoder()

df[zero_cols] = df[zero_cols].apply(label_encoder.fit_transform)

**One-Hot Encoder**

In [11]:
encoder = OneHotEncoder(sparse_output=False)

encoded_data = encoder.fit_transform(df[cols])

df_encoded = pd.DataFrame(encoded_data, columns = encoder.get_feature_names_out(cols))

df_encoded.head()

,cap-shape_b,cap-shape_c,cap-shape_f,cap-shape_k,cap-shape_s,cap-shape_x,cap-surface_f,cap-surface_g,cap-surface_s,cap-surface_y,...,population_s,population_v,population_y,habitat_d,habitat_g,habitat_l,habitat_m,habitat_p,habitat_u,habitat_w
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

Raqamlar bilan almashtirlgan ustunlarni tashlab yuboramiz

In [14]:
df = df.drop(cols, axis=1)

Ikkala datasetni yakuniy datasetga birlashtiramiz

In [17]:
df_final = pd.concat([df, df_encoded], axis=1)

Yakuniy datasetni saqlab olamiz

In [20]:
df_final.to_csv("../data/processed/mushrooms_cleaned.csv")